name: CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-publish-job:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python v3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Setup Poetry v1.1.13
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.13'

      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build

      - name: Publish to PyPi
        shell: bash
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish -vv --build -u '__token__' -p "$PYPI_TOKEN"
