name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-job:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

      - name: Setup Poetry v${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Show Poetry version
        run:  poetry --version

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config --list

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest

  generate-git-tag-job:
    name: Generate Git tag
    needs: build-and-test-job
    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Exibir hash do commit
        run: |
            export GIT_COMMITTER_NAME=$(git show -s --format='%cn')
            export GIT_COMMITTER_EMAIL=$(git show -s --format='%ce')
            export GIT_AUTHOR_NAME=$(git show -s --format='%an')
            export GIT_AUTHOR_EMAIL=$(git show -s --format='%ae')
            export COMMIT_HASH=$(git show -s --format='%H')
            export SUBJECT=$(git show -s --format='%s')
            env
