name: CI

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

      - name: Setup Poetry v${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Show Poetry version
        run:  poetry --version

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache-virtualenvs
        with:
          path: ~/.virtualenvs
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config --list

      - name: Install dependencies
        run: poetry install
        if: steps.cache-virtualenvs.outputs.cache-hit != 'true'

      - name: Test
        run: poetry run pytest
